[package]
name = "poisson-distribution-plotter"
version = "0.1.0"
authors=["FarerABR"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters="0.3.4"